name: CI Pipeline Run Tests on Push Code Changes
on:
  push:
    branches:    
    # Push events on master branch
    - master
    paths:
    # Changes to .JS or .JSON files (ie code or config changes)
    - '**.js'
    - '**.mjs'
    - '**.json'
    # Changes to GitHub CI Pipeline Actions (e.g. this Action!)
    - '**/.github/**/*.yml'
jobs:
  run-test-on-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: npm clean install, and test
      run: |
        npm ci
        npm test
      env:
        CI: true